Stripe integration
WelcometoMyGarden/welcometomygarden pull request #253
Opened 2022-12-05 18:01 UTC by th0rgall

2022-12-13 09:23 UTC, wardbeyens requested changes

2022-12-13 11:30 UTC, th0rgall commented on src/routes/become-superfan/+page.svelte
> +  function selectLevel(level: SuperfanLevelData) {
Noted, will change!

2022-12-13 11:30 UTC, th0rgall commented on src/routes/become-superfan/+page.svelte
> +</script>
Good question. This whole `become-superfan/+page.svelte` and `become-superfan/[id]/+page.svelte` is some messy copy-paste stuff.

I can imagine these levels can be useful in different parts of the app too, I'll try to move them somewhere to `lib`.

2022-12-13 11:34 UTC, th0rgall commented on src/routes/become-superfan/+page.svelte
> +      return goto(routes.SIGN_IN);
Good idea!

2022-12-13 11:35 UTC, th0rgall commented on src/routes/become-superfan/+page.svelte
> +<!-- TODO: find a way to generalize the wrapper across pages -->
Yep, I got the hang of slots yesterday, I already fixed this :)

2022-12-13 11:36 UTC, th0rgall commented on src/routes/become-superfan/payment/+page.svelte
> +      return goto(routes.SIGN_IN);
What do you mean with a guard?

2022-12-13 11:42 UTC, th0rgall commented on src/routes/become-superfan/payment/+page.svelte
> +  {#if $user && hasActiveSubscription($user)}
If I understood the docs correctly, I think you're wrong on this one :) 

https://svelte.dev/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values the docs don't mention that this doesn't work in templates
> Any time you have a reference to a store, you can access its value inside a component by prefixing it with the $ character. This causes Svelte to declare the prefixed variable, subscribe to the store at component initialization and unsubscribe when appropriate.
https://svelte.dev/docs#component-format-script-4-prefix-stores-with-$-to-access-their-values

And in this example, reactivity works in `App.svelte` without using $count in the <script>: https://svelte.dev/tutorial/auto-subscriptions

2022-12-13 11:44 UTC, th0rgall commented on src/lib/components/UI/SuperfanLevel.svelte
> +<script lang="ts">
Probably going to move this to `src/routes/(marketing)/_components`, if it's not going to be used elsewhere in the main app.

2022-12-14 16:28 UTC, wardbeyens commented on src/routes/become-superfan/payment/+page.svelte
> +      return goto(routes.SIGN_IN);
https://svelte.dev/repl/5673ff403af14411b0cd1785be3d996f?version=3.55.0

2022-12-14 19:45 UTC, th0rgall commented on src/lib/components/UI/SuperfanLevel.svelte
> +<script lang="ts">
> add component in /UI/index.js

I actually noticed this today several times: when opening import suggestions, I can often choose between the index.js export and the actual component export. What do you think is the benefit of having an index file?

2022-12-14 20:59 UTC, th0rgall commented on src/routes/become-superfan/payment/+page.svelte
> +      return goto(routes.SIGN_IN);
Hmm, that auth guard is just an alias for the same if statement that's there now. I think it's actually more simple with the if statement, with the auth guard you need to remember which slot names to use.

The UX here is not good though (client-side redirect, without warning). Should be improved.

2022-12-15 09:46 UTC, th0rgall commented on src/routes/become-superfan/+page.svelte
> +      return goto(routes.SIGN_IN);
Going to close this to move on and merge branches (clean up), the task is in Trello here: https://trello.com/c/EwHqiLi2/2805-superfan-payment-page

2022-12-15 09:47 UTC, merged