Preparation work for i18n
WelcometoMyGarden/welcometomygarden pull request #73
Opened 2020-08-10 11:59 UTC by auloin

Close #34

2020-08-11 14:05 UTC, wardbeyens commented
ready for review 😄
Internationalization for almost the entire website except for a few exceptional error messages. 

100% translated to dutch

2020-08-19 12:33 UTC, MichielLeyman requested changes
This is fantastic work @auloin and @wardbeyens, thank you!

The only thing I'd change before merging, is the numbering in legal titles being part of the translation. If we remove one, we wouldn't only have to change the translation across all files, we'd have to change all the subsequent title numbering as well.
It should either be determined through markup hierarchy with an ordered list (`<ol>`) or through array indexes. 

Example: 
```
"paragraphs": [
  {
    "title": "5.1 Offensive behaviour",
    "copy": []
  },
  {
    "title": "5.2 Indemnity",
    "copy": []
  }
]
```

2020-08-20 13:16 UTC, auloin commented on src/components/UI/Ol.svelte
> +<script>
Only decimal numbers are supported for now but it should be possible to make the component dynamic.

2020-08-28 10:27 UTC, MichielLeyman approved these changes

2020-08-28 10:28 UTC, merged