Location filter
WelcometoMyGarden/welcometomygarden pull request #78
Opened 2020-08-18 12:05 UTC by wardbeyens

closes #61

video: https://cloud.wabyte.com/index.php/s/JsmdbBdb5xxEJtq

The user types in the input field, if the user stops typing for 250 milliseconds then there are (normally) 5 results, i.e. 5 place names displayed below the input field.
These results appear and disappear with a fade-in (50ms) and fade-out (200ms).

If the user clicks on 1 of the results (i.e. 1 location) the map will zoom in to this location. The input field will be cleared and the results will disappear.

Currently the search is limited to cities and villages and the results are displayed in the language of the user.

If the user searches for a location and none is found a message "no places found" will be displayed for 3 seconds.

If the results are still on the screen, but the user clicks not on one of the locations, but on the map. Then the input field will be emptied as the results. (When the user drags the map, the locations WILL be displayed)

Future possibilities:
- accessibility, 'tab' 'shift tab' 'arrow up' 'arrow down' 'enter' => go over the places list, enter for selecting the place.
- dynamic zoom, search for Bruxelles zoom=10, search for small village zoom= 13 https://wiki.openstreetmap.org/wiki/Zoom_levels

known issue: 
- phone, while typing the search results are displayed over the trails box and not all the results are visible. (don't know how to fix)
link image not typing: https://cloud.wabyte.com/index.php/s/c3PKi7bPSPfwTsR
link image typing: https://cloud.wabyte.com/index.php/s/mK5K78L5MYyH84d

![](https://cloud.wabyte.com/index.php/s/mK5K78L5MYyH84d/preview)

2020-08-19 12:12 UTC, MichielLeyman commented
@wardbeyens we can't merge this without the filter button being finished right? Is this a draft?

2020-08-19 12:14 UTC, wardbeyens commented
Yes this is supposed to be a draft

2020-08-26 13:26 UTC, wardbeyens commented
closes #51

2020-08-26 13:28 UTC, wardbeyens commented
@MichielLeyman 
The filter feature is ready.
Both the location filter and the garden filter have been tested on different platforms and seem to work well.

2020-08-26 13:30 UTC, wardbeyens commented
> @wardbeyens we can't merge this without the filter button being finished right? Is this a draft?

Finished :smile:

2020-08-27 14:41 UTC, wardbeyens commented
The last 2 commits ensure that the map is centred on a user's garden, IP address, user's country with Belgium as fallback.

2020-09-01 10:55 UTC, MichielLeyman commented
Closes #55

2021-07-06 11:03 UTC, MichielLeyman commented
Closes #149

2021-07-18 21:21 UTC, MichielLeyman requested changes
@wardbeyens I'm working on getting this PR out the door finally, sorry for the delay on my end. When you have a spare moment, could you get the missing translations in (marked below) while I work on the location filtering and centering?

2021-07-18 21:21 UTC, MichielLeyman commented on src/components/Garden/Filter.svelte
> +  </span>
These still need translation

2021-07-18 21:21 UTC, MichielLeyman commented on src/components/Garden/FilterLocation.svelte
> +    <p>No places found</p>
This still needs translation

2021-07-18 21:21 UTC, MichielLeyman commented on src/components/UI/Modal.svelte
> +          <Button type="button" uppercase inverse on:click={close}>Close</Button>
This still needs translation

2021-07-22 20:55 UTC, wardbeyens commented on src/components/Garden/Filter.svelte
> +  </span>
damn i missed this one, will do!

2021-08-12 11:32 UTC, closed without merging